# This configuration file that create a logging configuration.
# This configuration defined two handler:
# - One that write to the console.
# - One that write to a rotating logfile.


logging:
  version: 1
  disable_existing_loggers: false
  # directory: E:\Find Changes Process\Staging\logs
  formatters:
    # One log format, used by both log handler.
    simple:
      format: "%(asctime)s-%(filename)s-Line: %(lineno)d-%(levelname)s-%(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    # The handler for the console.
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
    # The handler for the rotating file handler.
    file_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: INFO
      formatter: simple
      filename: sample.log
      encoding: utf8
      backupCount: 10
      when: midnight
  root:
    level: INFO
    handlers:
    - console
    - file_handler